---
- name: Copy shanred RDB snapshot with manual
  tags: copydb
  command:  aws --region "{{ region }}" rds copy-db-cluster-snapshot --source-db-cluster-snapshot-identifier arn:aws:rds:"{{ region }}":"{{ source-account }}":cluster-snapshot:"{{ snapshot-name }}" --target-db-cluster-snapshot-identifier "{{ new-snapshotname }}" --kms-key-id arn:aws:kms:us-east-2:122511138117:key/88bb6975-bed2-41d3-97b1-1a50baaab91d 

#################################################################
 
    #- name: sleep
  #  wait_for:
    #    timeout: 300
      #  delegate_to: localhost
  
    #- name: restoring the RDS snapshot
    #tags: restoring
    #command: aws rds modify-db-cluster-snapshot-attribute --region us-east-2 --db-cluster-snapshot-identifier "{{ snapshot-name }}" --attribute-name restore --values-to-add 122511138117
####################################################
