---

- hosts: my_app:bastian
  gather_facts: False
  strategy: free
  tasks:
    - include_role:
        name: "{{ rds_action }}"
#      when: "inventory_hostname == 'localhost_rds_backup' in groups['bastian']"

