---
- name: Run pre-script on EC2 instance
  service: name=httpd state=stopped
  become: yes
  become_method: sudo
  register: pre_script_output

- name: Print pre-script output
  debug:
    msg: "Pre-script output : {{ pre_script_output.stdout }}"
